import {
  GeocodingApiZip,
  GeocodingApiDirect,
  Onecall,
} from '../open-weather-types';

export async function geocodingByZip(zip: string): Promise<GeocodingApiZip> {
  if (zip === '98133') {
    return Promise.resolve({
      data: {
        country: 'US',
        lat: 47.7377,
        lon: -122.3431,
        name: 'Seattle',
        zip: '98133',
      },
    });
  }
  return Promise.reject('Mock cannot handle input');
}

export async function geocodingByCity(
  city: string
): Promise<GeocodingApiDirect> {
  if (city === 'gfdsgdsgj') {
    return Promise.resolve({ data: [] });
  } else if (city === 'Auburn') {
    return Promise.resolve({
      data: [
        {
          name: 'Auburn',
          local_names: {
            ar: 'أوبورن',
            ascii: 'Auburn',
            en: 'Auburn',
            fa: 'اوبرن، واشینگتن',
            feature_name: 'Auburn',
            ja: 'オーバーン',
            sr: 'Оберн',
          },
          lat: 47.3073,
          lon: -122.2284,
          country: 'US',
          state: 'WA',
        },
        {
          name: 'Auburn',
          local_names: {
            ar: 'أوبورن',
            ascii: 'Auburn',
            en: 'Auburn',
            fa: 'اوبرن، واشینگتن',
            feature_name: 'Auburn',
            ja: 'オーバーン',
            sr: 'Оберн',
          },
          lat: 47.3073,
          lon: -122.2284,
          country: 'US',
          state: 'WA',
        },
        {
          name: 'Auburn',
          local_names: {
            ar: 'أوبورن',
            ascii: 'Auburn',
            fa: 'آبرن، آلاباما',
            feature_name: 'Auburn',
            ja: 'オーバーン',
            ru: 'Оберн',
            sr: 'Оберн',
          },
          lat: 32.6099,
          lon: -85.4808,
          country: 'US',
          state: 'AL',
        },
        {
          name: 'Auburn',
          local_names: {
            ar: 'أوبورن',
            ascii: 'Auburn',
            bg: 'Обърн',
            en: 'Auburn',
            fa: 'آبورن، نیویورک',
            feature_name: 'Auburn',
            ja: 'オーバーン',
            ru: 'Оберн',
            sr: 'Оберн',
          },
          lat: 42.9317,
          lon: -76.566,
          country: 'US',
          state: 'NY',
        },
        {
          name: 'Auburn',
          local_names: {
            ar: 'أوبورن',
            ascii: 'Auburn',
            bg: 'Обърн',
            fa: 'ابرن، مین',
            feature_name: 'Auburn',
            ja: 'オーバーン',
            ru: 'Оберн',
            sr: 'Оберн',
          },
          lat: 44.0979,
          lon: -70.2312,
          country: 'US',
          state: 'ME',
        },
      ],
    });
  }
  return Promise.reject('Mock cannot handle input');
}

export async function onecall(
  lat: number,
  lon: number,
  exclude: string
): Promise<Onecall> {
  if (lat == 47.3073 && lon == -122.2284) {
    return Promise.resolve({
      data: {
        lat: 47.3073,
        lon: -122.2284,
        timezone: 'America/Los_Angeles',
        timezone_offset: -25200,
        current: {
          dt: 1635926195,
          sunrise: 1635951348,
          sunset: 1635986945,
          temp: 283.29,
          feels_like: 282.76,
          pressure: 1023,
          humidity: 92,
          dew_point: 282.05,
          uvi: 0,
          clouds: 100,
          visibility: 10000,
          wind_speed: 0.45,
          wind_deg: 115,
          wind_gust: 1.79,
          weather: [
            {
              id: 804,
              main: 'Clouds',
              description: 'overcast clouds',
              icon: '04n',
            },
          ],
        },
        hourly: [
          {
            dt: 1635922800,
            temp: 283.21,
            feels_like: 282.65,
            pressure: 1022,
            humidity: 91,
            dew_point: 281.81,
            uvi: 0,
            clouds: 100,
            visibility: 10000,
            wind_speed: 1.23,
            wind_deg: 95,
            wind_gust: 1.45,
            weather: [
              {
                id: 804,
                main: 'Clouds',
                description: 'overcast clouds',
                icon: '04n',
              },
            ],
            pop: 0,
          },
          {
            dt: 1635926400,
            temp: 283.29,
            feels_like: 282.76,
            pressure: 1023,
            humidity: 92,
            dew_point: 282.05,
            uvi: 0,
            clouds: 100,
            visibility: 10000,
            wind_speed: 0.66,
            wind_deg: 115,
            wind_gust: 0.81,
            weather: [
              {
                id: 804,
                main: 'Clouds',
                description: 'overcast clouds',
                icon: '04n',
              },
            ],
            pop: 0,
          },
          {
            dt: 1635930000,
            temp: 283.15,
            feels_like: 283.15,
            pressure: 1022,
            humidity: 91,
            dew_point: 281.75,
            uvi: 0,
            clouds: 100,
            visibility: 10000,
            wind_speed: 1.14,
            wind_deg: 131,
            wind_gust: 1.2,
            weather: [
              {
                id: 804,
                main: 'Clouds',
                description: 'overcast clouds',
                icon: '04n',
              },
            ],
            pop: 0,
          },
          {
            dt: 1635933600,
            temp: 282.84,
            feels_like: 282.84,
            pressure: 1022,
            humidity: 90,
            dew_point: 281.28,
            uvi: 0,
            clouds: 100,
            visibility: 10000,
            wind_speed: 1.29,
            wind_deg: 120,
            wind_gust: 1.32,
            weather: [
              {
                id: 804,
                main: 'Clouds',
                description: 'overcast clouds',
                icon: '04n',
              },
            ],
            pop: 0,
          },
          {
            dt: 1635937200,
            temp: 282.56,
            feels_like: 282.56,
            pressure: 1021,
            humidity: 89,
            dew_point: 280.84,
            uvi: 0,
            clouds: 100,
            visibility: 10000,
            wind_speed: 1.27,
            wind_deg: 114,
            wind_gust: 1.28,
            weather: [
              {
                id: 804,
                main: 'Clouds',
                description: 'overcast clouds',
                icon: '04n',
              },
            ],
            pop: 0,
          },
          {
            dt: 1635940800,
            temp: 281.93,
            feels_like: 281.93,
            pressure: 1020,
            humidity: 88,
            dew_point: 280.05,
            uvi: 0,
            clouds: 100,
            visibility: 10000,
            wind_speed: 0.89,
            wind_deg: 121,
            wind_gust: 0.97,
            weather: [
              {
                id: 804,
                main: 'Clouds',
                description: 'overcast clouds',
                icon: '04n',
              },
            ],
            pop: 0,
          },
          {
            dt: 1635944400,
            temp: 281.5,
            feels_like: 281.5,
            pressure: 1019,
            humidity: 87,
            dew_point: 279.15,
            uvi: 0,
            clouds: 95,
            visibility: 10000,
            wind_speed: 1.06,
            wind_deg: 113,
            wind_gust: 1.03,
            weather: [
              {
                id: 804,
                main: 'Clouds',
                description: 'overcast clouds',
                icon: '04n',
              },
            ],
            pop: 0,
          },
          {
            dt: 1635948000,
            temp: 281.35,
            feels_like: 281.35,
            pressure: 1019,
            humidity: 87,
            dew_point: 278.96,
            uvi: 0,
            clouds: 87,
            visibility: 10000,
            wind_speed: 1.23,
            wind_deg: 121,
            wind_gust: 1.21,
            weather: [
              {
                id: 804,
                main: 'Clouds',
                description: 'overcast clouds',
                icon: '04n',
              },
            ],
            pop: 0,
          },
          {
            dt: 1635951600,
            temp: 281.27,
            feels_like: 281.27,
            pressure: 1019,
            humidity: 87,
            dew_point: 278.81,
            uvi: 0,
            clouds: 91,
            visibility: 10000,
            wind_speed: 0.88,
            wind_deg: 105,
            wind_gust: 0.89,
            weather: [
              {
                id: 804,
                main: 'Clouds',
                description: 'overcast clouds',
                icon: '04d',
              },
            ],
            pop: 0,
          },
          {
            dt: 1635955200,
            temp: 282.48,
            feels_like: 282.48,
            pressure: 1018,
            humidity: 83,
            dew_point: 279.43,
            uvi: 0.09,
            clouds: 94,
            visibility: 10000,
            wind_speed: 0.75,
            wind_deg: 118,
            wind_gust: 0.8,
            weather: [
              {
                id: 804,
                main: 'Clouds',
                description: 'overcast clouds',
                icon: '04d',
              },
            ],
            pop: 0,
          },
          {
            dt: 1635958800,
            temp: 284.11,
            feels_like: 283.32,
            pressure: 1018,
            humidity: 79,
            dew_point: 280.28,
            uvi: 0.36,
            clouds: 95,
            visibility: 10000,
            wind_speed: 0.76,
            wind_deg: 89,
            wind_gust: 1.11,
            weather: [
              {
                id: 804,
                main: 'Clouds',
                description: 'overcast clouds',
                icon: '04d',
              },
            ],
            pop: 0,
          },
          {
            dt: 1635962400,
            temp: 285.33,
            feels_like: 284.61,
            pressure: 1017,
            humidity: 77,
            dew_point: 280.91,
            uvi: 0.75,
            clouds: 96,
            visibility: 10000,
            wind_speed: 0.68,
            wind_deg: 74,
            wind_gust: 1.2,
            weather: [
              {
                id: 804,
                main: 'Clouds',
                description: 'overcast clouds',
                icon: '04d',
              },
            ],
            pop: 0,
          },
          {
            dt: 1635966000,
            temp: 287.03,
            feels_like: 286.3,
            pressure: 1016,
            humidity: 70,
            dew_point: 281.33,
            uvi: 1.02,
            clouds: 100,
            visibility: 10000,
            wind_speed: 0.6,
            wind_deg: 7,
            wind_gust: 0.95,
            weather: [
              {
                id: 804,
                main: 'Clouds',
                description: 'overcast clouds',
                icon: '04d',
              },
            ],
            pop: 0,
          },
          {
            dt: 1635969600,
            temp: 287.58,
            feels_like: 286.88,
            pressure: 1015,
            humidity: 69,
            dew_point: 281.63,
            uvi: 1.19,
            clouds: 100,
            visibility: 10000,
            wind_speed: 0.94,
            wind_deg: 2,
            wind_gust: 1.53,
            weather: [
              {
                id: 804,
                main: 'Clouds',
                description: 'overcast clouds',
                icon: '04d',
              },
            ],
            pop: 0,
          },
          {
            dt: 1635973200,
            temp: 287.9,
            feels_like: 287.23,
            pressure: 1014,
            humidity: 69,
            dew_point: 281.87,
            uvi: 1.1,
            clouds: 100,
            visibility: 10000,
            wind_speed: 1.34,
            wind_deg: 294,
            wind_gust: 1.6,
            weather: [
              {
                id: 804,
                main: 'Clouds',
                description: 'overcast clouds',
                icon: '04d',
              },
            ],
            pop: 0,
          },
          {
            dt: 1635976800,
            temp: 285.95,
            feels_like: 285.32,
            pressure: 1013,
            humidity: 78,
            dew_point: 281.72,
            uvi: 0.5,
            clouds: 100,
            visibility: 10000,
            wind_speed: 1.19,
            wind_deg: 323,
            wind_gust: 1.5,
            weather: [
              {
                id: 804,
                main: 'Clouds',
                description: 'overcast clouds',
                icon: '04d',
              },
            ],
            pop: 0,
          },
          {
            dt: 1635980400,
            temp: 285.72,
            feels_like: 285.07,
            pressure: 1012,
            humidity: 78,
            dew_point: 281.67,
            uvi: 0.26,
            clouds: 100,
            visibility: 10000,
            wind_speed: 0.51,
            wind_deg: 156,
            wind_gust: 0.74,
            weather: [
              {
                id: 804,
                main: 'Clouds',
                description: 'overcast clouds',
                icon: '04d',
              },
            ],
            pop: 0,
          },
          {
            dt: 1635984000,
            temp: 285.38,
            feels_like: 284.75,
            pressure: 1011,
            humidity: 80,
            dew_point: 281.58,
            uvi: 0.09,
            clouds: 100,
            visibility: 10000,
            wind_speed: 0.41,
            wind_deg: 306,
            wind_gust: 0.66,
            weather: [
              {
                id: 804,
                main: 'Clouds',
                description: 'overcast clouds',
                icon: '04d',
              },
            ],
            pop: 0,
          },
          {
            dt: 1635987600,
            temp: 284.97,
            feels_like: 284.32,
            pressure: 1011,
            humidity: 81,
            dew_point: 281.44,
            uvi: 0,
            clouds: 100,
            visibility: 10000,
            wind_speed: 0.32,
            wind_deg: 315,
            wind_gust: 0.54,
            weather: [
              {
                id: 804,
                main: 'Clouds',
                description: 'overcast clouds',
                icon: '04n',
              },
            ],
            pop: 0.15,
          },
          {
            dt: 1635991200,
            temp: 284.7,
            feels_like: 284.05,
            pressure: 1010,
            humidity: 82,
            dew_point: 281.37,
            uvi: 0,
            clouds: 100,
            visibility: 10000,
            wind_speed: 0.88,
            wind_deg: 20,
            wind_gust: 0.91,
            weather: [
              {
                id: 804,
                main: 'Clouds',
                description: 'overcast clouds',
                icon: '04n',
              },
            ],
            pop: 0.29,
          },
          {
            dt: 1635994800,
            temp: 284.7,
            feels_like: 284.05,
            pressure: 1008,
            humidity: 82,
            dew_point: 281.37,
            uvi: 0,
            clouds: 100,
            visibility: 10000,
            wind_speed: 2.16,
            wind_deg: 75,
            wind_gust: 5.12,
            weather: [
              {
                id: 804,
                main: 'Clouds',
                description: 'overcast clouds',
                icon: '04n',
              },
            ],
            pop: 0.29,
          },
          {
            dt: 1635998400,
            temp: 284.59,
            feels_like: 283.9,
            pressure: 1006,
            humidity: 81,
            dew_point: 281.02,
            uvi: 0,
            clouds: 100,
            visibility: 10000,
            wind_speed: 1.24,
            wind_deg: 26,
            wind_gust: 2.06,
            weather: [
              {
                id: 804,
                main: 'Clouds',
                description: 'overcast clouds',
                icon: '04n',
              },
            ],
            pop: 0.23,
          },
          {
            dt: 1636002000,
            temp: 283.97,
            feels_like: 283.25,
            pressure: 1006,
            humidity: 82,
            dew_point: 280.68,
            uvi: 0,
            clouds: 100,
            visibility: 10000,
            wind_speed: 1.18,
            wind_deg: 13,
            wind_gust: 1.61,
            weather: [
              {
                id: 804,
                main: 'Clouds',
                description: 'overcast clouds',
                icon: '04n',
              },
            ],
            pop: 0.19,
          },
          {
            dt: 1636005600,
            temp: 283.88,
            feels_like: 283.18,
            pressure: 1005,
            humidity: 83,
            dew_point: 280.75,
            uvi: 0,
            clouds: 100,
            visibility: 10000,
            wind_speed: 0.78,
            wind_deg: 327,
            wind_gust: 1.49,
            weather: [
              {
                id: 804,
                main: 'Clouds',
                description: 'overcast clouds',
                icon: '04n',
              },
            ],
            pop: 0.21,
          },
          {
            dt: 1636009200,
            temp: 283.61,
            feels_like: 282.93,
            pressure: 1006,
            humidity: 85,
            dew_point: 280.86,
            uvi: 0,
            clouds: 100,
            visibility: 10000,
            wind_speed: 1.78,
            wind_deg: 195,
            wind_gust: 2.38,
            weather: [
              {
                id: 804,
                main: 'Clouds',
                description: 'overcast clouds',
                icon: '04n',
              },
            ],
            pop: 0.51,
          },
          {
            dt: 1636012800,
            temp: 283.18,
            feels_like: 282.64,
            pressure: 1005,
            humidity: 92,
            dew_point: 281.6,
            uvi: 0,
            clouds: 100,
            visibility: 10000,
            wind_speed: 1.76,
            wind_deg: 73,
            wind_gust: 3.82,
            weather: [
              {
                id: 501,
                main: 'Rain',
                description: 'moderate rain',
                icon: '10n',
              },
            ],
            pop: 0.85,
            rain: {
              '1h': 1.46,
            },
          },
          {
            dt: 1636016400,
            temp: 283.29,
            feels_like: 282.79,
            pressure: 1005,
            humidity: 93,
            dew_point: 281.76,
            uvi: 0,
            clouds: 100,
            visibility: 6475,
            wind_speed: 0.63,
            wind_deg: 161,
            wind_gust: 2.35,
            weather: [
              {
                id: 501,
                main: 'Rain',
                description: 'moderate rain',
                icon: '10n',
              },
            ],
            pop: 1,
            rain: {
              '1h': 1.12,
            },
          },
          {
            dt: 1636020000,
            temp: 283.85,
            feels_like: 283.38,
            pressure: 1003,
            humidity: 92,
            dew_point: 282.15,
            uvi: 0,
            clouds: 100,
            visibility: 10000,
            wind_speed: 1.2,
            wind_deg: 130,
            wind_gust: 3.99,
            weather: [
              {
                id: 500,
                main: 'Rain',
                description: 'light rain',
                icon: '10n',
              },
            ],
            pop: 1,
            rain: {
              '1h': 0.93,
            },
          },
          {
            dt: 1636023600,
            temp: 283.89,
            feels_like: 283.45,
            pressure: 1003,
            humidity: 93,
            dew_point: 282.35,
            uvi: 0,
            clouds: 100,
            visibility: 10000,
            wind_speed: 0.72,
            wind_deg: 150,
            wind_gust: 1.4,
            weather: [
              {
                id: 500,
                main: 'Rain',
                description: 'light rain',
                icon: '10n',
              },
            ],
            pop: 1,
            rain: {
              '1h': 0.15,
            },
          },
          {
            dt: 1636027200,
            temp: 283.45,
            feels_like: 282.99,
            pressure: 1003,
            humidity: 94,
            dew_point: 282.11,
            uvi: 0,
            clouds: 100,
            visibility: 10000,
            wind_speed: 0.8,
            wind_deg: 155,
            wind_gust: 1.02,
            weather: [
              {
                id: 804,
                main: 'Clouds',
                description: 'overcast clouds',
                icon: '04n',
              },
            ],
            pop: 0.8,
          },
          {
            dt: 1636030800,
            temp: 283.26,
            feels_like: 282.75,
            pressure: 1003,
            humidity: 93,
            dew_point: 281.86,
            uvi: 0,
            clouds: 81,
            visibility: 10000,
            wind_speed: 0.26,
            wind_deg: 153,
            wind_gust: 0.68,
            weather: [
              {
                id: 803,
                main: 'Clouds',
                description: 'broken clouds',
                icon: '04n',
              },
            ],
            pop: 0.56,
          },
          {
            dt: 1636034400,
            temp: 283.19,
            feels_like: 282.73,
            pressure: 1002,
            humidity: 95,
            dew_point: 282.05,
            uvi: 0,
            clouds: 83,
            visibility: 9150,
            wind_speed: 1.78,
            wind_deg: 89,
            wind_gust: 2.46,
            weather: [
              {
                id: 501,
                main: 'Rain',
                description: 'moderate rain',
                icon: '10n',
              },
            ],
            pop: 0.96,
            rain: {
              '1h': 1.13,
            },
          },
          {
            dt: 1636038000,
            temp: 283.37,
            feels_like: 282.93,
            pressure: 1002,
            humidity: 95,
            dew_point: 282.2,
            uvi: 0,
            clouds: 89,
            visibility: 7921,
            wind_speed: 0.58,
            wind_deg: 157,
            wind_gust: 1.02,
            weather: [
              {
                id: 501,
                main: 'Rain',
                description: 'moderate rain',
                icon: '10d',
              },
            ],
            pop: 1,
            rain: {
              '1h': 1.17,
            },
          },
          {
            dt: 1636041600,
            temp: 283.55,
            feels_like: 283.13,
            pressure: 1002,
            humidity: 95,
            dew_point: 282.39,
            uvi: 0.01,
            clouds: 91,
            visibility: 10000,
            wind_speed: 1.8,
            wind_deg: 100,
            wind_gust: 4.48,
            weather: [
              {
                id: 501,
                main: 'Rain',
                description: 'moderate rain',
                icon: '10d',
              },
            ],
            pop: 1,
            rain: {
              '1h': 1.86,
            },
          },
          {
            dt: 1636045200,
            temp: 284.88,
            feels_like: 284.41,
            pressure: 1002,
            humidity: 88,
            dew_point: 282.43,
            uvi: 0.04,
            clouds: 93,
            visibility: 10000,
            wind_speed: 3.05,
            wind_deg: 141,
            wind_gust: 10.6,
            weather: [
              {
                id: 500,
                main: 'Rain',
                description: 'light rain',
                icon: '10d',
              },
            ],
            pop: 1,
            rain: {
              '1h': 0.79,
            },
          },
          {
            dt: 1636048800,
            temp: 285.61,
            feels_like: 285.08,
            pressure: 1002,
            humidity: 83,
            dew_point: 282.38,
            uvi: 0.09,
            clouds: 94,
            visibility: 10000,
            wind_speed: 3.28,
            wind_deg: 149,
            wind_gust: 10.24,
            weather: [
              {
                id: 500,
                main: 'Rain',
                description: 'light rain',
                icon: '10d',
              },
            ],
            pop: 1,
            rain: {
              '1h': 0.27,
            },
          },
          {
            dt: 1636052400,
            temp: 286.02,
            feels_like: 285.53,
            pressure: 1003,
            humidity: 83,
            dew_point: 282.86,
            uvi: 0.18,
            clouds: 100,
            visibility: 10000,
            wind_speed: 3.94,
            wind_deg: 171,
            wind_gust: 11.5,
            weather: [
              {
                id: 500,
                main: 'Rain',
                description: 'light rain',
                icon: '10d',
              },
            ],
            pop: 0.92,
            rain: {
              '1h': 0.3,
            },
          },
          {
            dt: 1636056000,
            temp: 285.86,
            feels_like: 285.43,
            pressure: 1004,
            humidity: 86,
            dew_point: 283.26,
            uvi: 0.21,
            clouds: 100,
            visibility: 10000,
            wind_speed: 3.85,
            wind_deg: 167,
            wind_gust: 11.46,
            weather: [
              {
                id: 500,
                main: 'Rain',
                description: 'light rain',
                icon: '10d',
              },
            ],
            pop: 1,
            rain: {
              '1h': 0.83,
            },
          },
          {
            dt: 1636059600,
            temp: 286.76,
            feels_like: 286.4,
            pressure: 1004,
            humidity: 85,
            dew_point: 283.88,
            uvi: 0.19,
            clouds: 100,
            visibility: 10000,
            wind_speed: 3.71,
            wind_deg: 180,
            wind_gust: 11.42,
            weather: [
              {
                id: 500,
                main: 'Rain',
                description: 'light rain',
                icon: '10d',
              },
            ],
            pop: 1,
            rain: {
              '1h': 0.73,
            },
          },
          {
            dt: 1636063200,
            temp: 285.87,
            feels_like: 285.55,
            pressure: 1005,
            humidity: 90,
            dew_point: 283.96,
            uvi: 0.11,
            clouds: 100,
            visibility: 7783,
            wind_speed: 5.75,
            wind_deg: 208,
            wind_gust: 12.73,
            weather: [
              {
                id: 500,
                main: 'Rain',
                description: 'light rain',
                icon: '10d',
              },
            ],
            pop: 1,
            rain: {
              '1h': 0.88,
            },
          },
          {
            dt: 1636066800,
            temp: 285.03,
            feels_like: 284.57,
            pressure: 1007,
            humidity: 88,
            dew_point: 282.73,
            uvi: 0.06,
            clouds: 100,
            visibility: 10000,
            wind_speed: 6.46,
            wind_deg: 216,
            wind_gust: 14.08,
            weather: [
              {
                id: 500,
                main: 'Rain',
                description: 'light rain',
                icon: '10d',
              },
            ],
            pop: 1,
            rain: {
              '1h': 0.95,
            },
          },
          {
            dt: 1636070400,
            temp: 284.27,
            feels_like: 283.79,
            pressure: 1009,
            humidity: 90,
            dew_point: 282.23,
            uvi: 0.02,
            clouds: 100,
            visibility: 7200,
            wind_speed: 7.2,
            wind_deg: 212,
            wind_gust: 13.88,
            weather: [
              {
                id: 501,
                main: 'Rain',
                description: 'moderate rain',
                icon: '10d',
              },
            ],
            pop: 1,
            rain: {
              '1h': 1.34,
            },
          },
          {
            dt: 1636074000,
            temp: 283.78,
            feels_like: 283.2,
            pressure: 1012,
            humidity: 88,
            dew_point: 281.49,
            uvi: 0,
            clouds: 100,
            visibility: 10000,
            wind_speed: 6.61,
            wind_deg: 214,
            wind_gust: 13.87,
            weather: [
              {
                id: 501,
                main: 'Rain',
                description: 'moderate rain',
                icon: '10n',
              },
            ],
            pop: 0.88,
            rain: {
              '1h': 1.25,
            },
          },
          {
            dt: 1636077600,
            temp: 283.47,
            feels_like: 282.88,
            pressure: 1013,
            humidity: 89,
            dew_point: 281.42,
            uvi: 0,
            clouds: 100,
            visibility: 10000,
            wind_speed: 6.58,
            wind_deg: 219,
            wind_gust: 14.21,
            weather: [
              {
                id: 501,
                main: 'Rain',
                description: 'moderate rain',
                icon: '10n',
              },
            ],
            pop: 0.88,
            rain: {
              '1h': 1.08,
            },
          },
          {
            dt: 1636081200,
            temp: 283.17,
            feels_like: 282.45,
            pressure: 1014,
            humidity: 85,
            dew_point: 280.37,
            uvi: 0,
            clouds: 100,
            visibility: 10000,
            wind_speed: 5.97,
            wind_deg: 219,
            wind_gust: 13.27,
            weather: [
              {
                id: 500,
                main: 'Rain',
                description: 'light rain',
                icon: '10n',
              },
            ],
            pop: 0.88,
            rain: {
              '1h': 0.14,
            },
          },
          {
            dt: 1636084800,
            temp: 282.49,
            feels_like: 279.85,
            pressure: 1015,
            humidity: 87,
            dew_point: 279.99,
            uvi: 0,
            clouds: 100,
            visibility: 10000,
            wind_speed: 5.17,
            wind_deg: 208,
            wind_gust: 12.09,
            weather: [
              {
                id: 804,
                main: 'Clouds',
                description: 'overcast clouds',
                icon: '04n',
              },
            ],
            pop: 0.88,
          },
          {
            dt: 1636088400,
            temp: 282.09,
            feels_like: 279.62,
            pressure: 1016,
            humidity: 88,
            dew_point: 279.77,
            uvi: 0,
            clouds: 94,
            visibility: 10000,
            wind_speed: 4.5,
            wind_deg: 202,
            wind_gust: 11.22,
            weather: [
              {
                id: 804,
                main: 'Clouds',
                description: 'overcast clouds',
                icon: '04n',
              },
            ],
            pop: 0.88,
          },
          {
            dt: 1636092000,
            temp: 281.76,
            feels_like: 279.72,
            pressure: 1017,
            humidity: 88,
            dew_point: 279.44,
            uvi: 0,
            clouds: 84,
            visibility: 10000,
            wind_speed: 3.47,
            wind_deg: 197,
            wind_gust: 10.43,
            weather: [
              {
                id: 803,
                main: 'Clouds',
                description: 'broken clouds',
                icon: '04n',
              },
            ],
            pop: 0.88,
          },
        ],
        daily: [
          {
            dt: 1635966000,
            sunrise: 1635951348,
            sunset: 1635986945,
            moonrise: 1635945120,
            moonset: 1635985860,
            moon_phase: 0.96,
            temp: {
              day: 287.03,
              min: 281.27,
              max: 287.9,
              night: 283.88,
              eve: 284.97,
              morn: 281.5,
            },
            feels_like: {
              day: 286.3,
              night: 283.18,
              eve: 284.32,
              morn: 281.5,
            },
            pressure: 1016,
            humidity: 70,
            dew_point: 281.33,
            wind_speed: 2.16,
            wind_deg: 75,
            wind_gust: 5.12,
            weather: [
              {
                id: 804,
                main: 'Clouds',
                description: 'overcast clouds',
                icon: '04d',
              },
            ],
            clouds: 100,
            pop: 0.29,
            uvi: 1.19,
          },
          {
            dt: 1636052400,
            sunrise: 1636037839,
            sunset: 1636073258,
            moonrise: 1636036560,
            moonset: 1636073700,
            moon_phase: 0,
            temp: {
              day: 286.02,
              min: 281.76,
              max: 286.76,
              night: 281.76,
              eve: 283.78,
              morn: 283.26,
            },
            feels_like: {
              day: 285.53,
              night: 279.72,
              eve: 283.2,
              morn: 282.75,
            },
            pressure: 1003,
            humidity: 83,
            dew_point: 282.86,
            wind_speed: 7.2,
            wind_deg: 212,
            wind_gust: 14.21,
            weather: [
              {
                id: 501,
                main: 'Rain',
                description: 'moderate rain',
                icon: '10d',
              },
            ],
            clouds: 100,
            pop: 1,
            rain: 16.38,
            uvi: 0.21,
          },
          {
            dt: 1636138800,
            sunrise: 1636124329,
            sunset: 1636159572,
            moonrise: 1636128120,
            moonset: 1636161900,
            moon_phase: 0.04,
            temp: {
              day: 280.68,
              min: 277.79,
              max: 283.09,
              night: 277.79,
              eve: 281.92,
              morn: 281.23,
            },
            feels_like: {
              day: 278,
              night: 277.79,
              eve: 280.45,
              morn: 280.19,
            },
            pressure: 1018,
            humidity: 88,
            dew_point: 278.39,
            wind_speed: 5.53,
            wind_deg: 217,
            wind_gust: 11.64,
            weather: [
              {
                id: 501,
                main: 'Rain',
                description: 'moderate rain',
                icon: '10d',
              },
            ],
            clouds: 100,
            pop: 1,
            rain: 4.6,
            uvi: 0.94,
          },
          {
            dt: 1636225200,
            sunrise: 1636210820,
            sunset: 1636245888,
            moonrise: 1636219680,
            moonset: 1636250640,
            moon_phase: 0.07,
            temp: {
              day: 282.13,
              min: 277.59,
              max: 282.38,
              night: 279.89,
              eve: 281.12,
              morn: 277.96,
            },
            feels_like: {
              day: 279.09,
              night: 275.73,
              eve: 276.82,
              morn: 277.96,
            },
            pressure: 1007,
            humidity: 74,
            dew_point: 277.45,
            wind_speed: 9.4,
            wind_deg: 187,
            wind_gust: 22.04,
            weather: [
              {
                id: 501,
                main: 'Rain',
                description: 'moderate rain',
                icon: '10d',
              },
            ],
            clouds: 90,
            pop: 1,
            rain: 8.33,
            uvi: 0.56,
          },
          {
            dt: 1636311600,
            sunrise: 1636297311,
            sunset: 1636332205,
            moonrise: 1636310940,
            moonset: 1636340100,
            moon_phase: 0.11,
            temp: {
              day: 279.18,
              min: 276.97,
              max: 281.08,
              night: 276.97,
              eve: 279.69,
              morn: 278.92,
            },
            feels_like: {
              day: 276.15,
              night: 275.36,
              eve: 277.81,
              morn: 276.98,
            },
            pressure: 1018,
            humidity: 90,
            dew_point: 277.22,
            wind_speed: 5.24,
            wind_deg: 191,
            wind_gust: 12.84,
            weather: [
              {
                id: 501,
                main: 'Rain',
                description: 'moderate rain',
                icon: '10d',
              },
            ],
            clouds: 100,
            pop: 1,
            rain: 9.38,
            uvi: 1,
          },
          {
            dt: 1636398000,
            sunrise: 1636383802,
            sunset: 1636418525,
            moonrise: 1636401480,
            moonset: 1636430280,
            moon_phase: 0.15,
            temp: {
              day: 279.09,
              min: 275.06,
              max: 283.93,
              night: 278.5,
              eve: 281.84,
              morn: 275.06,
            },
            feels_like: {
              day: 279.09,
              night: 277.17,
              eve: 280.57,
              morn: 275.06,
            },
            pressure: 1015,
            humidity: 69,
            dew_point: 273.39,
            wind_speed: 2.3,
            wind_deg: 94,
            wind_gust: 6.23,
            weather: [
              {
                id: 804,
                main: 'Clouds',
                description: 'overcast clouds',
                icon: '04d',
              },
            ],
            clouds: 100,
            pop: 0.04,
            uvi: 1,
          },
          {
            dt: 1636484400,
            sunrise: 1636470293,
            sunset: 1636504846,
            moonrise: 1636491120,
            moonset: 1636521060,
            moon_phase: 0.19,
            temp: {
              day: 278.55,
              min: 278.06,
              max: 279.3,
              night: 278.17,
              eve: 279.3,
              morn: 278.72,
            },
            feels_like: {
              day: 275.81,
              night: 274.81,
              eve: 275.62,
              morn: 278.72,
            },
            pressure: 1006,
            humidity: 93,
            dew_point: 277.1,
            wind_speed: 5.7,
            wind_deg: 219,
            wind_gust: 12.13,
            weather: [
              {
                id: 501,
                main: 'Rain',
                description: 'moderate rain',
                icon: '10d',
              },
            ],
            clouds: 100,
            pop: 1,
            rain: 9.81,
            uvi: 1,
          },
          {
            dt: 1636570800,
            sunrise: 1636556783,
            sunset: 1636591169,
            moonrise: 1636579980,
            moonset: 1636612020,
            moon_phase: 0.23,
            temp: {
              day: 280.49,
              min: 277.08,
              max: 283.49,
              night: 278.74,
              eve: 281.61,
              morn: 277.08,
            },
            feels_like: {
              day: 280.49,
              night: 278.74,
              eve: 281.61,
              morn: 275.33,
            },
            pressure: 1022,
            humidity: 77,
            dew_point: 276.3,
            wind_speed: 2.64,
            wind_deg: 192,
            wind_gust: 8.87,
            weather: [
              {
                id: 500,
                main: 'Rain',
                description: 'light rain',
                icon: '10d',
              },
            ],
            clouds: 98,
            pop: 0.97,
            rain: 1.62,
            uvi: 1,
          },
        ],
      },
    });
  }
  return Promise.reject('Mock cannot handle input');
}
